<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            margin: 0;
            padding: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #333;
        }

        .header .subtitle {
            margin: 5px 0;
            color: #666;
            font-size: 14px;
        }

        .meta-info {
            margin-bottom: 20px;
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
        }

        .meta-info table {
            width: 100%;
            border-collapse: collapse;
        }

        .meta-info td {
            padding: 5px 10px;
            border: none;
        }

        .section {
            margin-bottom: 30px;
        }

        .section h3 {
            color: #333;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
            margin-bottom: 15px;
        }

        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }

        .data-table th,
        .data-table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        .data-table th {
            background-color: #007bff;
            color: white;
            font-weight: bold;
        }

        .data-table tr:nth-child(even) {
            background-color: #f8f9fa;
        }

        .stats-grid {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }

        .stats-row {
            display: table-row;
        }

        .stats-cell {
            display: table-cell;
            padding: 15px;
            border: 1px solid #ddd;
            background-color: #f8f9fa;
            text-align: center;
            width: 25%;
        }

        .stats-cell strong {
            display: block;
            font-size: 18px;
            color: #007bff;
            margin-bottom: 5px;
        }

        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }

        .no-data {
            text-align: center;
            color: #666;
            font-style: italic;
            margin: 40px 0;
        }
    </style>
</head>

<body>
    <!-- Header -->
    <div class="header">
        <h1>{{ $title }}</h1>
        <div class="subtitle">Information Management System for Capiz Rehabilitation Center</div>
        <div class="subtitle">Generated on {{ $generated_at }}</div>
    </div>

    <!-- Meta Information -->
    <div class="meta-info">
        <table>
            <tr>
                <td><strong>Generated by:</strong> {{ $generated_by }}</td>
                <td><strong>Report Type:</strong> {{ $report->type }}</td>
            </tr>
            <tr>
                <td><strong>Report Date:</strong> {{ $generated_at }}</td>
                <td><strong>Description:</strong> {{ $report->description ?? 'N/A' }}</td>
            </tr>
        </table>
    </div>

    <!-- Report Content -->
    @if (isset($data['statistics']))
        <div class="section">
            <h3>Statistics Summary</h3>
            @if (isset($data['statistics']['summary']))
                <div class="stats-grid">
                    <div class="stats-row">
                        <div class="stats-cell">
                            <strong>{{ $data['statistics']['summary']['total_pdls'] ?? 0 }}</strong>
                            <span>Total PDLs</span>
                        </div>
                        @if (isset($data['statistics']['summary']['by_status']))
                            @foreach ($data['statistics']['summary']['by_status'] as $status => $count)
                                <div class="stats-cell">
                                    <strong>{{ $count }}</strong>
                                    <span>{{ ucfirst($status) }}</span>
                                </div>
                            @endforeach
                        @endif
                    </div>
                </div>
            @endif
        </div>
    @endif

    @if (isset($data['pdls']) && $data['pdls']->count() > 0)
        <div class="section">
            <h3>PDL Records</h3>
            <table class="data-table">
                <thead>
                    <tr>
                        @php
                            $fields = $report->getFields();
                        @endphp
                        @if (in_array('pdl_number', $fields))
                            <th>PDL Number</th>
                        @endif
                        @if (in_array('name', $fields))
                            <th>Full Name</th>
                        @endif
                        @if (in_array('age', $fields))
                            <th>Age</th>
                        @endif
                        @if (in_array('gender', $fields))
                            <th>Gender</th>
                        @endif
                        @if (in_array('status', $fields))
                            <th>Status</th>
                        @endif
                        @if (in_array('legal_status', $fields))
                            <th>Legal Status</th>
                        @endif
                        @if (in_array('admission_date', $fields))
                            <th>Admission Date</th>
                        @endif
                    </tr>
                </thead>
                <tbody>
                    @foreach ($data['pdls'] as $pdl)
                        <tr>
                            @if (in_array('pdl_number', $fields))
                                <td>{{ $pdl->pdl_number }}</td>
                            @endif
                            @if (in_array('name', $fields))
                                <td>{{ $pdl->full_name ?? $pdl->first_name . ' ' . $pdl->last_name }}</td>
                            @endif
                            @if (in_array('age', $fields))
                                <td>{{ $pdl->age ?? 'N/A' }}</td>
                            @endif
                            @if (in_array('gender', $fields))
                                <td>{{ ucfirst($pdl->gender ?? 'N/A') }}</td>
                            @endif
                            @if (in_array('status', $fields))
                                <td>{{ $pdl->status ?? 'N/A' }}</td>
                            @endif
                            @if (in_array('legal_status', $fields))
                                <td>{{ $pdl->legal_status ?? 'N/A' }}</td>
                            @endif
                            @if (in_array('admission_date', $fields))
                                <td>{{ $pdl->admission_date ? $pdl->admission_date->format('M j, Y') : 'N/A' }}</td>
                            @endif
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    @endif

    @if ((!isset($data['pdls']) || $data['pdls']->count() == 0) && !isset($data['statistics']))
        <div class="no-data">
            <p>No data available for this report configuration.</p>
        </div>
    @endif

    <!-- Parameters Used -->
    @if (!empty($parameters))
        <div class="section">
            <h3>Report Parameters</h3>
            <div class="meta-info">
                <table>
                    @foreach ($parameters as $key => $value)
                        <tr>
                            <td><strong>{{ ucfirst(str_replace('_', ' ', $key)) }}:</strong></td>
                            <td>
                                @if (is_array($value))
                                    {{ implode(', ', $value) }}
                                @elseif(is_object($value))
                                    {{ json_encode($value) }}
                                @else
                                    {{ $value }}
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
        </div>
    @endif

    <!-- Footer -->
    <div class="footer">
        <p>This custom report was generated automatically by the IMSCRC system on {{ $generated_at }}.</p>
        <p>Report Template: {{ $report->name }} (ID: {{ $report->id }})</p>
        <p>For questions or concerns, please contact the system administrator.</p>
    </div>
</body>

</html>
