<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            margin: 0;
            padding: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #333;
        }

        .header .subtitle {
            margin: 5px 0;
            color: #666;
            font-size: 14px;
        }

        .meta-info {
            margin-bottom: 20px;
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
        }

        .meta-info table {
            width: 100%;
            border-collapse: collapse;
        }

        .meta-info td {
            padding: 5px 10px;
            border: none;
        }

        .statistics {
            margin-bottom: 30px;
        }

        .statistics h3 {
            color: #333;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
        }

        .stats-grid {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }

        .stats-row {
            display: table-row;
        }

        .stats-cell {
            display: table-cell;
            padding: 10px;
            border: 1px solid #ddd;
            background-color: #f8f9fa;
            text-align: center;
            width: 25%;
        }

        .stats-cell strong {
            display: block;
            font-size: 18px;
            color: #007bff;
        }

        .pdl-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        .pdl-table th,
        .pdl-table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        .pdl-table th {
            background-color: #007bff;
            color: white;
            font-weight: bold;
        }

        .pdl-table tr:nth-child(even) {
            background-color: #f8f9fa;
        }

        .status-badge {
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 10px;
            font-weight: bold;
            text-transform: uppercase;
        }

        .status-active {
            background-color: #28a745;
            color: white;
        }

        .status-inactive {
            background-color: #6c757d;
            color: white;
        }

        .status-transferred {
            background-color: #17a2b8;
            color: white;
        }

        .legal-status-badge {
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 10px;
            font-weight: bold;
        }

        .legal-detained {
            background-color: #ffc107;
            color: #212529;
        }

        .legal-convicted {
            background-color: #dc3545;
            color: white;
        }

        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }

        .page-break {
            page-break-before: always;
        }
    </style>
</head>

<body>
    <!-- Header -->
    <div class="header">
        <h1>{{ $title }}</h1>
        <div class="subtitle">Information Management System for Capiz Rehabilitation Center</div>
        <div class="subtitle">Generated on {{ $generated_at }}</div>
    </div>

    <!-- Meta Information -->
    <div class="meta-info">
        <table>
            <tr>
                <td><strong>Generated by:</strong> {{ $generated_by }}</td>
                <td><strong>Total Records:</strong> {{ $total_count }}</td>
            </tr>
            <tr>
                <td><strong>Report Date:</strong> {{ $generated_at }}</td>
                <td><strong>Filters Applied:</strong>
                    @if (empty($parameters))
                        None
                    @else
                        @if (isset($parameters['status']))
                            Status: {{ implode(', ', $parameters['status']) }}
                        @endif
                        @if (isset($parameters['legal_status']))
                            Legal Status: {{ implode(', ', $parameters['legal_status']) }}
                        @endif
                        @if (isset($parameters['date_range']))
                            Date Range: {{ $parameters['date_range']['start'] ?? 'N/A' }} to
                            {{ $parameters['date_range']['end'] ?? 'N/A' }}
                        @endif
                    @endif
                </td>
            </tr>
        </table>
    </div>

    <!-- Statistics Summary -->
    <div class="statistics">
        <h3>Summary Statistics</h3>
        <div class="stats-grid">
            <div class="stats-row">
                <div class="stats-cell">
                    <strong>{{ $statistics['total'] }}</strong>
                    <span>Total PDLs</span>
                </div>
                <div class="stats-cell">
                    <strong>{{ $statistics['by_gender']['male'] ?? 0 }}</strong>
                    <span>Male</span>
                </div>
                <div class="stats-cell">
                    <strong>{{ $statistics['by_gender']['female'] ?? 0 }}</strong>
                    <span>Female</span>
                </div>
                <div class="stats-cell">
                    <strong>{{ $statistics['recent_admissions'] }}</strong>
                    <span>Recent Admissions (30 days)</span>
                </div>
            </div>
        </div>

        @if (isset($statistics['by_status']) && count($statistics['by_status']) > 0)
            <h4>Status Breakdown</h4>
            <div class="stats-grid">
                <div class="stats-row">
                    @foreach ($statistics['by_status'] as $status => $count)
                        <div class="stats-cell">
                            <strong>{{ $count }}</strong>
                            <span>{{ ucfirst($status) }}</span>
                        </div>
                    @endforeach
                </div>
            </div>
        @endif

        @if (isset($statistics['by_legal_status']) && count($statistics['by_legal_status']) > 0)
            <h4>Legal Status Breakdown</h4>
            <div class="stats-grid">
                <div class="stats-row">
                    @foreach ($statistics['by_legal_status'] as $legalStatus => $count)
                        <div class="stats-cell">
                            <strong>{{ $count }}</strong>
                            <span>{{ ucfirst($legalStatus) }}</span>
                        </div>
                    @endforeach
                </div>
            </div>
        @endif
    </div>

    <!-- PDL Records Table -->
    @if ($pdls->count() > 0)
        <div class="page-break">
            <h3>PDL Records</h3>
            <table class="pdl-table">
                <thead>
                    <tr>
                        <th>PDL Number</th>
                        <th>Full Name</th>
                        <th>Age</th>
                        <th>Gender</th>
                        <th>Status</th>
                        <th>Legal Status</th>
                        <th>Admission Date</th>
                        <th>Case Number</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($pdls as $pdl)
                        <tr>
                            <td>{{ $pdl->pdl_number }}</td>
                            <td>{{ $pdl->full_name ?? $pdl->first_name . ' ' . $pdl->last_name }}</td>
                            <td>{{ $pdl->age ?? 'N/A' }}</td>
                            <td>{{ ucfirst($pdl->gender ?? 'N/A') }}</td>
                            <td>
                                <span class="status-badge status-{{ strtolower($pdl->status ?? 'unknown') }}">
                                    {{ $pdl->status ?? 'Unknown' }}
                                </span>
                            </td>
                            <td>
                                <span
                                    class="legal-status-badge legal-{{ strtolower($pdl->legal_status ?? 'unknown') }}">
                                    {{ $pdl->legal_status ?? 'Unknown' }}
                                </span>
                            </td>
                            <td>{{ $pdl->admission_date ? $pdl->admission_date->format('M j, Y') : 'N/A' }}</td>
                            <td>{{ $pdl->case_number ?? 'N/A' }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    @else
        <div class="no-data">
            <p style="text-align: center; color: #666; font-style: italic; margin: 40px 0;">
                No PDL records found matching the specified criteria.
            </p>
        </div>
    @endif

    <!-- Footer -->
    <div class="footer">
        <p>This report was generated automatically by the IMSCRC system on {{ $generated_at }}.</p>
        <p>For questions or concerns, please contact the system administrator.</p>
    </div>
</body>

</html>
